### PR TITLE
Precise relative time ago changes

### PR DESCRIPTION
**Pull request by onishiweb**
New PR after reverting #49 because there was discussion missed over the change to precise relative time.

@ironsidevsquincy can you add your thoughts behind the changes please.

### CODE REVIEW

**Comment by onishiweb** [comment]
@wheresrhys as you initially implemented the Moment style relative times, would you care to comment on your preference?

**Comment by onishiweb** [comment]
Discussion on the Moment repo: https://github.com/moment/moment/issues/348

**Comment by JakeChampion** [comment]
The reasoning for sticking with <90 for an hour ago is because it makes more sense to users to see `an hour ago` rather than `61 minutes ago`. Users don't usually need to know exactly when an article was published, only a rough indication. Exact timings can be found by hovering on the timestamp IIRC.

**Comment by wheresrhys** [comment]
yep what Jake said. 

I imagine whether to round to the hour or use exact minutes depends on context sometimes. If there are use cases for using exact minutes, can we list them in these comments, and possibly make that behaviour opt-inable by means of a data-attribute `data-o-date--precise`

**Comment by ironsidevsquincy** [comment]
@JakeChampion This PR doesn't change that, 61 minutes will still say 'an hour ago'. This changes the oddness (IMHO) of something being 45 minutes ago and us displaying 'an hour ago' (it now displays '45 minutes ago). And the same applies for all the other units of time (days/weeks/etc)

**Comment by ironsidevsquincy** [comment]
Plus can't depend on hover states in our touchscreen world

**Comment by wheresrhys** [comment]
It's still odd to round 1.30 down to 'an hour' but not round 59 up to 'an hour', no?

**Comment by JakeChampion** [comment]
It also changes 1hr 55mins to be 1 hour ago rather than 2 hours ago, right?

**Comment by wheresrhys** [comment]
Why are we doing this? User feedback? Data? Product/editorial pressure? Current format looks weird for fastft? ...?

**Comment by ironsidevsquincy** [comment]
Personally, no, think that's natural, it happened an hour ago, plus change. But I can see how this is getting into subjective territory here

Yep, feedback from the front-page team, using o-date on the next front page and the times look odd - none of us thought displaying something that happened 45 minutes ago as `an hour ago` made sense, but obviously open to understanding why it works like this (other than because it's the way moment works)

**Comment by wheresrhys** [comment]
I don't feel very strongly either way, though I don't think behaviour of a component used across lots of FT products should come down to one team's opinion of what looks right in one context

**Comment by JakeChampion** [comment]
I think this may be better answered by a member of the UX department

**Comment by ironsidevsquincy** [comment]
We absolutely should not dictate the way this component works, hence why I put it in this PR hoping to get people's feedback and opinions, i.e. this

**Comment by alicebartlett** [comment]
OK it seems like we're deep into developer reckons territory here, so I'm going to talk to UX folk and see if we can get a proper position on this.

**Comment by alicebartlett** [comment]
OK, chatted with Joe Dollar Smirnoff and within the team about this.

This PR makes some improvements to code clarity so we'll keep those. I'm going to raise an issue with the decided behaviour which someone can then implement, along with the improvements to readability that darren made here.

**Pull request closed without merging**
