### PR TITLE
Refactor for testing

### PR DESCRIPTION
**Pull request by alicebartlett**
This PR refactors some parts of o-date's main.js so that (in a later PR) the tests can be rewritten to be more readable, and provide better coverage.

This commit: moves some repeated logic into separate public testable functions: 
`isYesterday(date, date, interval)`, `isToday(date, date, interval)`, `isNearFuture(interval)` and `isFarFuture(interval)` and `getSecondsBetween(time, othertime)`.

Making these public means we can write tests for these individual functions rather than having to write a lot of logic in a single test to test things like ftTime properly. Happy to bikeshed on the names / behaviours of some of these functions, particularly isNearFuture and isFarFuture which i think could be improved.

Following this being merged (and still passing the old tests) I'll open a new pr with the new tests.

### CODE REVIEW

**Comment by onishiweb** [comment]
👍  Looks good. Refactor looks really clean and easier to follow now. 

`isNearFuture` and `isFarFuture` are a bit odd naming wise, but once I'd read the comments they seemed to make sense. Some of the previous comments like "allow for reasonable difference in machine clocks" were a bit more helpful in understanding why we might get a future date though? Could be worth keeping those.

**Comment by alicebartlett** [comment]
@onishiweb good point, I'll take a look at the comments we lost

**Comment by rowanmanning** [comment]
This looks great, should be way easier to test with these changes 👍

**Comment by onishiweb** [comment]
👍

**Pull request merged**
