### PR TITLE
Update origamiCategory to primitives

### PR DESCRIPTION
**Pull request by chee**
https://github.com/Financial-Times/origami-website/issues/180

### CODE REVIEW

**Comment by JakeChampion** [comment]
CircleCI has been removed, if you amend the commit or make another commit, the build error from CircleCI will disappear.

**Comment by origamiserviceuser** [comment]
o-date bundle size difference from 4.0.4 to 154583fdaa73ca0b324418458eb3b65917e42797
No bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-date bundle size difference from 4.0.4 to 9766cbee93e9dc1dfffebafc1c03494811e6b04f
No bundle size differences found.

**Comment by JakeChampion** [comment]
:tada: This PR is included in version v4.0.5 :tada:

**Comment by origamiserviceuser** [comment]
o-date bundle size difference from 4.0.4 to 99b7dca9270e0b0b1bb63db852889d97c300ac57
No bundle size differences found.

**Pull request merged**
