### PR TITLE
Move range used by ftTime to make it configurable.

### PR DESCRIPTION
**Pull request by antoligy**
Hey,

Use-case:
For NAR, given ambiguity around timezones, stakeholders would like for the standard FT Time behaviour with the relative-hours range increased from 4 hours to 6.

This is a quick-and-dirty first pass at making the range configurable.  There are nicer ways of doing this.  Open to suggestions on how to make this better, and the conversation about whether or not this is a supported use-case.

### CODE REVIEW

**Comment by rowanmanning** [comment]
This seems like a sensible workaround to me. Are any of the Origami team adverse to it? It's quite nit-picky, but you _could_ add it as `oDate.ftTime.relativeHoursInSeconds` as it's only used by that function.

Other than that, mentioning the ability to do this in the docs would be handy. Thanks :)

**Comment by JakeChampion** [comment]
The new setting needs to be configurable via a data attribute as well for users who choose declarative markup over using their own JavaScript.

**Comment by antoligy** [comment]
Cheers @rowanmanning, I've updated that.  Test suite isn't running presumably because this isn't a local fork.

@JakeChampion Agreed, I think that should be okay.
I was a bit hesitant about changing how the formatting, so would a new (data?) attribute make more sense? `duration="3600"` or something like that?

**Comment by alicebartlett** [comment]
(I've checked it out and pushed the same branch to this repo so the tests will run against it)

**Comment by alicebartlett** [comment]
@antoligy A new data attribute to configure this via the markup would be really good so our build service users can take advantage of this feature. 

eg
`<time data-o-component=o-date data-o-date-format="ft-time" data-o-date-ft-time-limit="3600"></>

(Although I notice `data-o-date-format="ft-time"`doesn't actually do anything, it would just pass through to the final else)

**Comment by JakeChampion** [comment]
Hi @antoligy, is this feature still wanted by ouyrself and/or NAR?

**Pull request closed without merging**
